workflows:
  ios-workflow:
    name: iOS Build

    environment:
      node: 20
      xcode: latest

    scripts:
      - npm install --legacy-peer-deps

      # إنشاء iOS من الصفر
      - npx cap add ios || true
      - npx cap sync ios

      # تأكد أن المشروع موجود
      - ls ios/App

      - cd ios/App
      - pod install
      - cd ../..

    artifacts:
      - build/ios/ipa/*.ipa