apply plugin: 'com.android.application'

android {
    namespace "adalt7dy.mar.com"
    compileSdk 35

    defaultConfig {
        applicationId "adalt7dy.mar.com"
        minSdk 23
        targetSdk 35
        versionCode 20
        versionName "2.4.22"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':capacitor-android')
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.activity:activity:1.9.2'
    implementation 'androidx.fragment:fragment:1.8.4'
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.2.0'
    implementation project(':capacitor-community-admob')

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}